# Generated by Django 6.0.6 on 2026-06-14 20:04

import posts.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_markdown', models.TextField(help_text='Write your technical updates or logs here.')),
                ('canvas_image', models.ImageField(blank=True, null=True, upload_to=posts.models.get_upload_path)),
                ('author_signature', models.TextField(blank=True, help_text='Cryptographic signature of the post content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
