# Generated by Django 6.0.6 on 2026-06-14 21:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('art', 'Digital Art'), ('general', 'General Updates')], default='general', max_length=15),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'created_at'], name='posts_post_categor_ef64e4_idx'),
        ),
    ]
