# Generated by Django 6.0.6 on 2026-06-21 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('tech_stack', models.CharField(blank=True, help_text='Enter languages separated by spaces, e.g. Python Django Tailwind', max_length=200)),
                ('github_url', models.URLField(blank=True)),
                ('avatar_color', models.CharField(default='#4f46e5', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
