# Generated by Django 6.0.6 on 2026-06-15 22:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=255)),
                ('escrow_budget', models.DecimalField(decimal_places=2, help_text='Funds locked in platform escrow', max_digits=10)),
                ('requirements_markdown', models.TextField(help_text='Detailed brand deliverables for the creator')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('active', 'Contract Active'), ('completed', 'Campaign Fulfilled'), ('declined', 'Declined by Creator')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
