# Generated by Django 6.0.6 on 2026-06-14 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(error_messages={'unique': 'This email is already registered on the waitlist.'}, max_length=255, unique=True)),
                ('username', models.CharField(error_messages={'unique': 'This username is already reserved.'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Usernames must be 3-30 characters and contain only letters, numbers, or underscores.', regex='^[a-zA-Z0-9_]{3,30}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
